### PR TITLE
Add UIController script to GameController object

### PR DESCRIPTION
**Pull request by mandeep**
This fixes the problem where the main menu UI elements weren't active.

### CODE REVIEW

**Comment by mandeep** [comment]
This also changes GameController to TurnController in Planet.cs so that the players are put on top of the planet.

**Comment by matthewachan** [comment]
Looks good to me. If it breaks, blame Mandeep.

**Comment by mandeep** [comment]
End Turn still does not work. Let's fix this and add it to this PR.

**Comment by huy-ha** [comment]
I'm very disappointed in you guys

**Comment by mandeep** [comment]
End Turn is now fixed, but we are debugging Attack.

**Comment by mandeep** [comment]
Ok, everything seems to be working now. Ready for review.

**Comment by matthewachan** [comment]
Reviewed by Huy and he says it looks great.

**Pull request merged**
